os: Windows Server 2012

environment:
  EnableNuGetPackageRestore: true

install:
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    appveyor-retry nuget restore